class Config:    
    NETWORK_NAME = '<NETWORK-NAME>'
    NETWORK_KEY = '<NETWORK-KEY>'
    SITE_ID = '<SITE-ID>'
    SITE_KEY = '<SITE-KEY>'
    COLLECTION_ID = '<COLLECTION-ID>'
    USER_ID = '<USER-ID>'
    ARTICLE_ID = '<ARTICLE-ID>'